### ISSUE TITLE
Tests not working on ruby 3.4

### ISSUE THREAD

**Issue by Segaja** [dmendel/bindata#161]
```
200 OK

A new release of RubyGems is available: 3.6.2 → 3.6.7!
Run `gem update --system 3.6.7` to update your installation.

removed 'tmp_install/usr/lib/ruby/gems/3.4.0/cache/bindata-2.5.0.gem'
removed directory 'tmp_install/usr/lib/ruby/gems/3.4.0/cache/'
==> Starting check()...
Resolving dependencies...
Run options: --seed 1566

# Running:

..............................................................................................................................
/build/ruby-bindata/src/bindata/lib/bindata/io.rb:459: warning: literal string will be frozen in the future (run with --debug-
/build/ruby-bindata/src/bindata/lib/bindata/io.rb:459: warning: literal string will be frozen in the future (run with --debug-
..............................................................................................................................

Finished in 0.561143s, 1334.7764 runs/s, 14789.4651 assertions/s.

  1) Error:
BinData::Primitive::when defining with errors#test_0003_fails when field name shadows an existing method:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

  2) Error:
BinData::Primitive::when defining with errors#test_0002_fails on duplicate names:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

  3) Error:
BinData::Primitive::when defining with errors#test_0004_fails on unknown endian:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

  4) Error:
BinData::Primitive::when defining with errors#test_0001_fails on non registered types:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

  5) Error:
BinData::Record::when defining with errors#test_0003_gives correct error message for non registered nested types in blocks:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

  6) Error:
BinData::Record::when defining with errors#test_0007_fails on reserved names:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

  7) Error:
BinData::Record::when defining with errors#test_0004_fails on nested choice when missing names:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

  8) Error:
BinData::Record::when defining with errors#test_0002_gives correct error message for non registered nested types:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

  9) Error:
BinData::Record::when defining with errors#test_0010_fails when endian is after a field:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

 10) Error:
BinData::Record::when defining with errors#test_0011_fails when search_prefix is after a field:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

 11) Error:
BinData::Record::when defining with errors#test_0001_fails on non registered types:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

 12) Error:
BinData::Record::when defining with errors#test_0006_fails on duplicate names:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

 13) Error:
BinData::Record::when defining with errors#test_0008_fails when field name shadows an existing method:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

 14) Error:
BinData::Record::when defining with errors#test_0009_fails on unknown endian:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

 15) Error:
BinData::Record::when defining with errors#test_0005_fails on malformed names:
NoMethodError: undefined method '+' for nil
    test/test_helper.rb:50:in 'Minitest::Assertions#assert_raises_on_line'

749 runs, 8299 assertions, 0 failures, 15 errors, 0 skips
Coverage report generated for Unit Tests to /build/ruby-bindata/src/bindata/coverage.
Line Coverage: 99.07% (5769 / 5823)
Branch Coverage: 97.12% (606 / 624)
rake aborted!
Command failed with status (1)

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by loqs** [comment]
Additional Information:
Versions:
```
$ ruby --version
ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [x86_64-linux]
```
Steps to reproduce:
```
$ curl -L -o ruby-bindata-2.4.14.tar.gz  https://github.com/dmendel/bindata/archive/v2.4.14/ruby-bindata-v2.4.14.tar.gz
$ tar -xf ruby-bindata-2.4.14.tar.gz
$ cd ruby-bindata-2.4.14
$ bundle install --path="$srcdir"
$ bundle exec rake test --verbose
Use TESTOPTS="--verbose" to pass --verbose, etc. to runners.
/build/ruby-bindata/src/ruby/3.4.0/gems/minitest-5.11.3/lib/minitest/mock.rb:31: warning: redefining 'object_id' may cause serious problems
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Run options: --seed 53886

# Running:

..........................................................................................................................................................................................................................................................................EEEE.......................................................................................................................................................EEEEEEEEEEE..............................................................................................................................................................................................................................................................................................................................

Finished in 0.248786s, 3014.6371 runs/s, 33454.4329 assertions/s.

  1) Error:
BinData::Primitive::when defining with errors#test_0002_fails on duplicate names:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/primitive_test.rb:42:in 'block (2 levels) in <top (required)>'

  2) Error:
BinData::Primitive::when defining with errors#test_0003_fails when field name shadows an existing method:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/primitive_test.rb:50:in 'block (2 levels) in <top (required)>'

  3) Error:
BinData::Primitive::when defining with errors#test_0001_fails on non registered types:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/primitive_test.rb:32:in 'block (2 levels) in <top (required)>'

  4) Error:
BinData::Primitive::when defining with errors#test_0004_fails on unknown endian:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/primitive_test.rb:58:in 'block (2 levels) in <top (required)>'

  5) Error:
BinData::Record::when defining with errors#test_0004_fails on nested choice when missing names:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:48:in 'block (2 levels) in <top (required)>'

  6) Error:
BinData::Record::when defining with errors#test_0010_fails when endian is after a field:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:101:in 'block (2 levels) in <top (required)>'

  7) Error:
BinData::Record::when defining with errors#test_0003_gives correct error message for non registered nested types in blocks:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:37:in 'block (2 levels) in <top (required)>'

  8) Error:
BinData::Record::when defining with errors#test_0011_fails when search_prefix is after a field:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:110:in 'block (2 levels) in <top (required)>'

  9) Error:
BinData::Record::when defining with errors#test_0008_fails when field name shadows an existing method:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:84:in 'block (2 levels) in <top (required)>'

 10) Error:
BinData::Record::when defining with errors#test_0001_fails on non registered types:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:19:in 'block (2 levels) in <top (required)>'

 11) Error:
BinData::Record::when defining with errors#test_0005_fails on malformed names:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:57:in 'block (2 levels) in <top (required)>'

 12) Error:
BinData::Record::when defining with errors#test_0006_fails on duplicate names:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:67:in 'block (2 levels) in <top (required)>'

 13) Error:
BinData::Record::when defining with errors#test_0007_fails on reserved names:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:76:in 'block (2 levels) in <top (required)>'

 14) Error:
BinData::Record::when defining with errors#test_0009_fails on unknown endian:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:92:in 'block (2 levels) in <top (required)>'

 15) Error:
BinData::Record::when defining with errors#test_0002_gives correct error message for non registered nested types:
NoMethodError: undefined method '+' for nil
    /build/ruby-bindata/src/bindata-2.4.14/test/test_helper.rb:46:in 'Kernel#must_raise_on_line'
    /build/ruby-bindata/src/bindata-2.4.14/test/record_test.rb:27:in 'block (2 levels) in <top (required)>'

750 runs, 8323 assertions, 0 failures, 15 errors, 0 skips
[Coveralls] Outside the CI environment, not sending data.
rake aborted!
Command failed with status (1)
/build/ruby-bindata/src/ruby/3.4.0/gems/rake-13.2.1/exe/rake:27:in '<top (required)>'
/usr/bin/bundle:25:in 'Kernel#load'
/usr/bin/bundle:25:in '<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by dmendel** [comment]
Thank you for the report. Fixed in BinData 2.5.1
